INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (1, 'To Kill a Mockingbird', 'Harper Lee', 10.99, 'Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (2, '1984', 'George Orwell', 9.99, 'Dystopian', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (3, 'Pride and Prejudice', 'Jane Austen', 8.99, 'Romance', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (4, 'The Great Gatsby', 'F. Scott Fitzgerald', 10.49, 'Classic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (5, 'Moby-Dick', 'Herman Melville', 11.99, 'Adventure', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (6, 'War and Peace', 'Leo Tolstoy', 12.99, 'Historical Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (7, 'The Odyssey', 'Homer', 9.49, 'Epic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (8, 'Crime and Punishment', 'Fyodor Dostoevsky', 10.99, 'Psychological Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (9, 'The Catcher in the Rye', 'J.D. Salinger', 8.49, 'Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (10, 'The Lord of the Rings', 'J.R.R. Tolkien', 15.99, 'Fantasy', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (11, 'Jane Eyre', 'Charlotte Brontë', 9.99, 'Gothic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (12, 'Brave New World', 'Aldous Huxley', 9.99, 'Dystopian', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (13, 'The Hobbit', 'J.R.R. Tolkien', 8.99, 'Fantasy', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (14, 'Anna Karenina', 'Leo Tolstoy', 11.49, 'Classic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (15, 'The Adventures of Huckleberry Finn', 'Mark Twain', 7.99, 'Adventure', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (16, 'Fahrenheit 451', 'Ray Bradbury', 8.49, 'Science Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (17, 'Wuthering Heights', 'Emily Brontë', 9.49, 'Gothic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (18, 'The Divine Comedy', 'Dante Alighieri', 12.99, 'Epic Poetry', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (19, 'Hamlet', 'William Shakespeare', 6.99, 'Tragedy', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (20, 'The Iliad', 'Homer', 9.49, 'Epic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (21, 'The Brothers Karamazov', 'Fyodor Dostoevsky', 11.99, 'Philosophical Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (22, 'One Hundred Years of Solitude', 'Gabriel García Márquez', 10.99, 'Magical Realism', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (23, 'The Grapes of Wrath', 'John Steinbeck', 9.99, 'Historical Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (24, 'The Picture of Dorian Gray', 'Oscar Wilde', 7.99, 'Philosophical Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (25, 'Dracula', 'Bram Stoker', 8.99, 'Horror', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (26, 'Les Misérables', 'Victor Hugo', 12.49, 'Historical Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (27, 'Don Quixote', 'Miguel de Cervantes', 11.99, 'Classic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (28, 'The Alchemist', 'Paulo Coelho', 9.49, 'Adventure', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (29, 'The Old Man and the Sea', 'Ernest Hemingway', 7.49, 'Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (30, 'Catch-22', 'Joseph Heller', 9.99, 'Satire', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (31, 'Moby Dick', 'Herman Melville', 10.99, 'Adventure', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (32, 'The Stranger', 'Albert Camus', 8.99, 'Philosophical Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (33, 'The Little Prince', 'Antoine de Saint-Exupéry', 6.99, 'Children\'s', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (34, 'Beloved', 'Toni Morrison', 9.49, 'Historical Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (35, 'Ulysses', 'James Joyce', 12.99, 'Modernist', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (36, 'The Sound and the Fury', 'William Faulkner', 9.99, 'Southern Gothic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (37, 'Lolita', 'Vladimir Nabokov', 8.99, 'Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (38, 'Meditations', 'Marcus Aurelius', 7.49, 'Philosophy', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (39, 'Frankenstein', 'Mary Shelley', 8.49, 'Science Fiction', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (40, 'The Count of Monte Cristo', 'Alexandre Dumas', 11.49, 'Adventure', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (41, 'Great Expectations', 'Charles Dickens', 9.99, 'Classic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (42, 'Jane Eyre', 'Charlotte Brontë', 9.49, 'Gothic', true);
INSERT INTO Book (id, title, author_name, price, genre, is_book_available) VALUES (43, 'The Secret Garden', 'Frances Hodgson Burnett', 7.49, 'Children\'s', true);