spring:
  application:
    name: User-Service

  datasource:
    url: jdbc:mysql://localhost:3306/pocket_book
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    database:
      platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  register-with-eureka: true
  fetch-registry: true



server:
  port: 8081